export 'package:flutter/material.dart';
export 'package:resume_builder_app/routes/routes_utils.dart';
export 'package:resume_builder_app/Views/BuildOptionPage/AllOptions/Education/education_info_page.dart';
export '../Views/BuildOptionPage/AllOptions/Achivement/achivement_page.dart';
export '../Views/BuildOptionPage/AllOptions/Career Objective Page/career_objective_page.dart';
export '../Views/BuildOptionPage/AllOptions/Contact_info_page/contact_info_page.dart';
export '../Views/BuildOptionPage/AllOptions/Experience/experience_page.dart';
export '../Views/BuildOptionPage/build_option_page.dart';
export '../Views/Home Page/home_page.dart';
export '../Views/SplashScreen/splash_screen.dart';
export 'dart:async';
export 'package:flutter/services.dart';
export '../Views/BuildOptionPage/AllOptions/Declaration/declaration_page.dart';
export '../Views/BuildOptionPage/AllOptions/Hobbies/hobby_page.dart';
export '../Views/BuildOptionPage/AllOptions/Personal Details/personal_detail_page.dart';
export '../Views/BuildOptionPage/AllOptions/Project/project_page.dart';
export '../Views/BuildOptionPage/AllOptions/Reference/reference_page.dart';
export '../Views/BuildOptionPage/AllOptions/Technical Skill/technical_skill_page.dart';
export '../../../../Utils/Globals.dart';
export '../Views/PDF/pdf_page.dart';
export 'package:resume_builder_app/extension/extension.dart';
